owner: CarnivoreKR
repo: status

sites:
  - name: update.carnivore.kr
    url: https://update.carnivore.kr/
  - name: go.carnivore.kr
    url: https://go.carnivore.kr/
  - name: share.carnivore.kr
    url: https://share.carnivore.kr/
    
status-website:
  cname: status.carnivore.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | Carnivore Korea
  introTitle: "**Status** for Carnivore Korea"
  introMessage: 카니보어 코리아 웹모니터
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Update
      href: https://go.carnivore.kr/update
    - title: Community
      href: https://go.carnivore.kr/community
